# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

######  GENERAL WORD DATABASE  ######

# Gets rid of user added words too IF I rake db:seed
Word.destroy_all

Word.create(word: 'Esoteric', cat: 'adjective')
Word.create(word: 'Exorbitant', cat: 'adjective')
Word.create(word: 'Self-righteous', cat: 'adjective')
Word.create(word: 'Surreptitious', cat: 'adjective')
Word.create(word: 'Dazzling', cat: 'adjective')
Word.create(word: 'Enigmatic', cat: 'adjective')
Word.create(word: 'Clouded', cat: 'adjective')
Word.create(word: 'Hermetical', cat: 'adjective')
Word.create(word: 'Sequestered', cat: 'adjective')
Word.create(word: 'Cryptic', cat: 'adjective')
Word.create(word: 'Magnanimous', cat: 'adjective')
Word.create(word: 'Classic', cat: 'adjective')
Word.create(word: 'Periwinkle', cat: 'adjective')
Word.create(word: 'Cerulean', cat: 'adjective')
Word.create(word: 'Indigo', cat: 'adjective')
Word.create(word: 'Crimson', cat: 'adjective')
Word.create(word: 'Auroral', cat: 'adjective')
Word.create(word: 'Burnished', cat: 'adjective')
Word.create(word: 'Brazen', cat: 'adjective')
Word.create(word: 'Silvery', cat: 'adjective')
Word.create(word: 'Resplendent', cat: 'adjective')
Word.create(word: 'Ardent', cat: 'adjective')
Word.create(word: 'Zealous', cat: 'adjective')
Word.create(word: 'Fervid', cat: 'adjective')
Word.create(word: 'Spirited', cat: 'adjective')
Word.create(word: 'Smoldering', cat: 'adjective')
Word.create(word: 'Clandestine', cat: 'adjective')
Word.create(word: 'Hoppy', cat: 'adjective')
Word.create(word: 'Serendipidous', cat: 'adjective')
Word.create(word: 'Apathetic', cat: 'adjective')
Word.create(word: 'Tame', cat: 'adjective')
Word.create(word: 'West Coast', cat: 'adjective')
Word.create(word: 'Manly', cat: 'adjective')
Word.create(word: 'Burly', cat: 'adjective')
Word.create(word: 'Maximum', cat: 'adjective')
Word.create(word: 'Yoked', cat: 'adjective')
Word.create(word: 'Banal', cat: 'adjective')
Word.create(word: 'Insipid', cat: 'adjective')
Word.create(word: 'Hapless', cat: 'adjective')
Word.create(word: 'Vanilla', cat: 'adjective')
Word.create(word: 'Arid', cat: 'adjective')
Word.create(word: 'Coy', cat: 'adjective')
Word.create(word: 'Bashful', cat: 'adjective')
Word.create(word: 'Crestfallen', cat: 'adjective')
Word.create(word: 'Forlorn', cat: 'adjective')
Word.create(word: 'Forgotten', cat: 'adjective')
Word.create(word: 'Meek', cat: 'adjective')
Word.create(word: 'Modest', cat: 'adjective')
Word.create(word: 'Arogant', cat: 'adjective')
Word.create(word: 'Audacious', cat: 'adjective')
Word.create(word: 'Worried', cat: 'adjective')
Word.create(word: 'Cavalier', cat: 'adjective')
Word.create(word: 'Dapper', cat: 'adjective')
Word.create(word: 'Blushing', cat: 'adjective')
Word.create(word: 'Superlicious', cat: 'adjective')
Word.create(word: 'Coquettish', cat: 'adjective')
Word.create(word: 'Demure', cat: 'adjective')
Word.create(word: 'Wayward', cat: 'adjective')
Word.create(word: 'Backwards', cat: 'adjective')
Word.create(word: 'Tenacious', cat: 'adjective')
Word.create(word: 'Egyptian', cat: 'adjective')
Word.create(word: 'Dudley', cat: 'adjective')
Word.create(word: 'Scorned', cat: 'adjective')
Word.create(word: 'Scornful', cat: 'adjective')
Word.create(word: 'Woeful', cat: 'adjective')
Word.create(word: 'Contemtuous', cat: 'adjective')
Word.create(word: 'Spiffy', cat: 'adjective')
Word.create(word: 'Striped', cat: 'adjective')
Word.create(word: 'Unintented', cat: 'adjective')
Word.create(word: 'Unintentional', cat: 'adjective')


Word.create(word: 'Mugwort', cat: 'noun')
Word.create(word: 'Death Eater', cat: 'noun')
Word.create(word: 'Queen Bee', cat: 'noun')
Word.create(word: 'Trout', cat: 'noun')
Word.create(word: 'Mackerel', cat: 'noun')
Word.create(word: 'Water Lily', cat: 'noun')
Word.create(word: 'Tiger Lily', cat: 'noun')
Word.create(word: 'Flamingo', cat: 'noun')
Word.create(word: 'Barrel', cat: 'noun')
Word.create(word: 'Squid', cat: 'noun')
Word.create(word: 'Steer', cat: 'noun')
Word.create(word: 'Maiden', cat: 'noun')
Word.create(word: 'Ox', cat: 'noun')
Word.create(word: 'Gentleman', cat: 'noun')
Word.create(word: 'Anchor', cat: 'noun')
Word.create(word: 'Impala', cat: 'noun')
Word.create(word: 'Hands', cat: 'noun')
Word.create(word: 'Boot', cat: 'noun')
Word.create(word: 'Ruby', cat: 'noun')
Word.create(word: 'Beard', cat: 'noun')
Word.create(word: 'Hype', cat: 'noun')
Word.create(word: 'Tripe', cat: 'noun')
Word.create(word: 'Spectre', cat: 'noun')
Word.create(word: 'Orchid', cat: 'noun')
Word.create(word: 'O-Matic', cat: 'noun')
Word.create(word: 'Station', cat: 'noun')
Word.create(word: 'Wreck', cat: 'noun')
Word.create(word: 'Bane', cat: 'noun')
Word.create(word: 'Basilisk', cat: 'noun')
Word.create(word: 'Forest', cat: 'noun')
Word.create(word: 'Chamber', cat: 'noun')
Word.create(word: 'Carriage', cat: 'noun')
Word.create(word: 'Abel', cat: 'noun')
Word.create(word: 'Adam', cat: 'noun')
Word.create(word: 'Bryan', cat: 'noun')
Word.create(word: 'Cassie', cat: 'noun')
Word.create(word: 'Christine', cat: 'noun')
Word.create(word: 'Ezra', cat: 'noun')
Word.create(word: 'Gabe', cat: 'noun')
Word.create(word: 'Jaytee', cat: 'noun')
Word.create(word: 'Jeong', cat: 'noun')
Word.create(word: 'Kevin', cat: 'noun')
Word.create(word: 'Kimberly', cat: 'noun')
Word.create(word: 'Maria', cat: 'noun')
Word.create(word: 'Meghan', cat: 'noun')
Word.create(word: 'Paula', cat: 'noun')
Word.create(word: 'Philip', cat: 'noun')
Word.create(word: 'Prity', cat: 'noun')
Word.create(word: 'Rachelle', cat: 'noun')
Word.create(word: 'Richard', cat: 'noun')
Word.create(word: 'Samuel', cat: 'noun')
Word.create(word: 'Tara', cat: 'noun')
Word.create(word: 'Taylor', cat: 'noun')
Word.create(word: 'Tiffany', cat: 'noun')
Word.create(word: 'William', cat: 'noun')
Word.create(word: 'Dayrit', cat: 'noun')
Word.create(word: 'Chang', cat: 'noun')
Word.create(word: 'Harwood', cat: 'noun')
Word.create(word: 'Milch', cat: 'noun')
Word.create(word: 'Claney', cat: 'noun')
Word.create(word: 'Montero', cat: 'noun')
Word.create(word: 'Herrera', cat: 'noun')
Word.create(word: 'Patel', cat: 'noun')
Word.create(word: 'Howley', cat: 'noun')
Word.create(word: 'Burke', cat: 'noun')
Word.create(word: 'Joseph', cat: 'noun')
Word.create(word: 'Nguyen', cat: 'noun')
Word.create(word: 'Yi', cat: 'noun')
Word.create(word: 'Tran', cat: 'noun')
Word.create(word: 'Lawrence', cat: 'noun')
Word.create(word: 'Huelsmann', cat: 'noun')
Word.create(word: 'Lee', cat: 'noun')
Word.create(word: 'Sanchez', cat: 'noun')
Word.create(word: 'Kim', cat: 'noun')
Word.create(word: 'Raez', cat: 'noun')
Word.create(word: 'Meinders', cat: 'noun')
Word.create(word: 'Purtlebaugh', cat: 'noun')
Word.create(word: 'Garza', cat: 'noun')
Word.create(word: 'Zinker', cat: 'noun')
Word.create(word: 'Hernandez', cat: 'noun')
Word.create(word: 'Hughes', cat: 'noun')
Word.create(word: 'Stanley', cat: 'noun')
Word.create(word: 'Yang', cat: 'noun')










def generate_words
  Word.where(:cat => "adjective").sample.word + " " + Word.where(:cat => "noun").sample.word
end
